### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by KaySackey** [dbeck/scalesmall#1]
The documentation links on the README don't point to anything publicly accessible.

**Comment by dbeck** [comment]
Thanks for pointing out. I am in the process of refactoring the docs and the code.
I just fixed it. Standalone components are available through hex.pm:
- [Chatter](https://hex.pm/packages/chatter)
- [GroupManager](https://hex.pm/packages/group_manager)

The current component responsible for the message queue is under design / development resides under the stream_pipe application. That one is not even alpha. Mostly exists  in my hand written notes :)
